import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { Leaf, Bus, UtensilsCrossed, GraduationCap, Map, Search, Bot, BookOpen, Award, TrendingUp, Zap, Shield, ArrowRight, ChevronRight, Globe, Users, Target, Star, MessageSquare, PlayCircle } from 'lucide-react'
import { motion, useScroll, useTransform, AnimatePresence } from 'framer-motion'

const FEATURES = [
  { icon: Leaf, title: 'Carbon Tracker', desc: 'Real-time footprint monitoring across all campus activities.', color: '#16a34a' },
  { icon: Bus, title: 'Live Transit', desc: 'Precision GPS tracking for all university shuttle routes.', color: '#0ea5e9' },
  { icon: UtensilsCrossed, title: 'Eco-Cafeteria', desc: 'Pre-order meals and view sustainability impact ratings.', color: '#f59e0b' },
  { icon: GraduationCap, title: 'Smart Presence', desc: 'Seamless QR-based attendance and digital identity.', color: '#a855f7' },
  { icon: BookOpen, title: 'AI Study Sync', desc: 'Personalized study plans generated by neural networks.', color: '#14b8a6' },
  { icon: Bot, title: 'Nexus AI', desc: '24/7 intelligent assistance for all campus queries.', color: '#ef4444' },
]

const STATS = [
  { label: 'CO2 Offset', value: '24,500', unit: 'kg', icon: Globe },
  { label: 'Active Students', value: '12,200', unit: '+', icon: Users },
  { label: 'Eco Projects', value: '85', unit: '', icon: Target },
]

export default function LandingPage() {
  const navigate = useNavigate()
  const { scrollY } = useScroll()
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const updateScrolled = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', updateScrolled)
    return () => window.removeEventListener('scroll', updateScrolled)
  }, [])

  const opacity = useTransform(scrollY, [0, 400], [1, 0])
  const scale = useTransform(scrollY, [0, 400], [1, 0.9])

  return (
    <div className="min-h-screen bg-slate-950 text-white selection:bg-green-500/30 overflow-x-hidden">
      {/* Background Decorative Elements */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-0 right-[-10%] w-[50%] h-[50%] rounded-full bg-green-500/10 blur-[150px] animate-pulse" />
        <div className="absolute bottom-0 left-[-10%] w-[50%] h-[50%] rounded-full bg-blue-500/10 blur-[150px] animate-pulse" style={{ animationDelay: '2s' }} />
        <div className="absolute top-[30%] left-[20%] w-[20%] h-[20%] rounded-full bg-purple-500/5 blur-[100px]" />
      </div>

      {/* NAVBAR */}
      <nav className={`fixed top-0 left-0 w-full z-[100] transition-all duration-500 ${
        scrolled ? 'py-3 backdrop-blur-xl bg-slate-950/80 border-b border-white/5' : 'py-6 bg-transparent'
      }`}>
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="InstitutePulse Logo" className="w-10 h-10 object-contain shadow-lg shadow-green-500/20" />
            <span className="text-xl font-black tracking-tighter bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
              INSTITUTE<span className="text-green-500">PULSE</span>
            </span>
          </div>
          
          <div className="hidden md:flex items-center gap-8">
            {['Features', 'About', 'Ecosystem', 'Support'].map(item => (
              <a key={item} href={`#${item.toLowerCase()}`} className="text-xs font-bold uppercase tracking-widest text-gray-400 hover:text-white transition-colors">
                {item}
              </a>
            ))}
          </div>

          <div className="flex items-center gap-4">
            <button 
              onClick={() => navigate('/login')}
              className="px-6 py-2.5 text-xs font-black uppercase tracking-widest hover:text-green-500 transition-colors"
            >
              Log In
            </button>
            <button 
              onClick={() => navigate('/register')}
              className="px-6 py-2.5 bg-white text-slate-950 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-green-500 hover:text-white transition-all shadow-lg shadow-white/5"
            >
              Get Started
            </button>
          </div>
        </div>
      </nav>

      {/* HERO SECTION */}
      <section className="relative pt-40 pb-20 px-6 z-10 overflow-hidden">
        <motion.div 
          style={{ opacity, scale }}
          className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"
        >
          <div>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20 mb-6"
            >
              <Zap size={14} className="text-green-500" />
              <span className="text-[10px] font-black uppercase tracking-[0.2em] text-green-500">The Future of Campus Life</span>
            </motion.div>
            
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-6xl md:text-8xl font-black leading-[0.9] tracking-tighter mb-8"
            >
              Elevate Your <br />
              <span className="bg-gradient-to-r from-green-400 to-emerald-600 bg-clip-text text-transparent">University Experience</span>
            </motion.h1>
            
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="text-lg text-gray-400 max-w-lg mb-10 leading-relaxed font-medium"
            >
              The unified operating system for smart, sustainable campus living. Track your impact, navigate seamlessly, and unlock AI-powered tools.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="flex flex-wrap gap-4"
            >
              <button 
                onClick={() => navigate('/register')}
                className="group px-8 py-4 bg-green-600 rounded-2xl flex items-center gap-3 shadow-2xl shadow-green-600/20 hover:bg-green-500 transition-all"
              >
                <span className="font-black uppercase tracking-widest text-sm">Join the Ecosystem</span>
                <ChevronRight size={20} className="group-hover:translate-x-1 transition-transform" />
              </button>
              <button className="px-8 py-4 bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl flex items-center gap-3 hover:bg-white/10 transition-all">
                <PlayCircle size={20} className="text-green-500" />
                <span className="font-black uppercase tracking-widest text-sm">Watch Demo</span>
              </button>
            </motion.div>
          </div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="relative"
          >
            {/* Visual element representing the system */}
            <div className="relative z-10 rounded-[40px] border border-white/10 p-4 bg-white/5 backdrop-blur-sm overflow-hidden shadow-2xl">
               <div className="bg-slate-900 rounded-[32px] aspect-[4/3] relative overflow-hidden flex flex-col items-center justify-center p-8">
                  <div className="absolute inset-0 bg-gradient-to-br from-green-500/20 to-transparent" />
                  <img src="/logo.png" alt="System Interface" className="w-48 h-48 object-contain mb-6 animate-pulse" />
                  <div className="grid grid-cols-2 gap-4 w-full">
                    {[1, 2, 3, 4].map(i => (
                      <div key={i} className="h-2 rounded-full bg-white/5 overflow-hidden">
                        <motion.div 
                          animate={{ x: ['-100%', '100%'] }} 
                          transition={{ duration: 2, repeat: Infinity, delay: i * 0.5 }}
                          className="h-full w-1/2 bg-green-500/40" 
                        />
                      </div>
                    ))}
                  </div>
               </div>
            </div>
            {/* Floating badges */}
            <motion.div 
              animate={{ y: [0, -10, 0] }} 
              transition={{ duration: 4, repeat: Infinity }}
              className="absolute top-[-20px] left-[-20px] z-20 px-4 py-2 rounded-xl bg-white/10 backdrop-blur-md border border-white/20 flex items-center gap-2"
            >
              <Award size={16} className="text-yellow-500" />
              <span className="text-[10px] font-black uppercase tracking-widest">Top Eco App 2026</span>
            </motion.div>
            <motion.div 
              animate={{ y: [0, 10, 0] }} 
              transition={{ duration: 5, repeat: Infinity }}
              className="absolute bottom-10 right-[-30px] z-20 px-4 py-2 rounded-xl bg-green-600 border border-green-500 flex items-center gap-2 shadow-xl shadow-green-600/30"
            >
              <TrendingUp size={16} className="text-white" />
              <span className="text-[10px] font-black uppercase tracking-widest">12.5k Active Daily</span>
            </motion.div>
          </motion.div>
        </motion.div>
      </section>

      {/* STATS SECTION */}
      <section className="py-20 px-6 border-y border-white/5 relative z-10">
        <div className="max-w-7xl mx-auto flex flex-wrap justify-center gap-12 md:gap-32">
          {STATS.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              transition={{ delay: i * 0.1 }}
              className="text-center"
            >
              <div className="flex items-center justify-center gap-2 mb-2">
                <stat.icon size={20} className="text-green-500" />
                <span className="text-4xl md:text-5xl font-black">{stat.value}{stat.unit}</span>
              </div>
              <p className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-500">{stat.label}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* FEATURES GRID */}
      <section id="features" className="py-32 px-6 relative z-10">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <h2 className="text-4xl md:text-6xl font-black tracking-tighter mb-6">Built for the Modern Campus</h2>
            <p className="text-gray-400 max-w-xl mx-auto font-medium">A unified platform that brings together sustainability, security, and smart services in one beautiful interface.</p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {FEATURES.map((feature, i) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                whileHover={{ y: -5 }}
                className="group p-8 rounded-[32px] bg-white/5 border border-white/5 hover:border-green-500/20 transition-all relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
                  <feature.icon size={100} />
                </div>
                <div 
                  className="w-14 h-14 rounded-2xl flex items-center justify-center mb-6 shadow-lg transition-transform group-hover:rotate-12"
                  style={{ backgroundColor: `${feature.color}15`, color: feature.color }}
                >
                  <feature.icon size={28} />
                </div>
                <h3 className="text-xl font-black mb-3">{feature.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed font-medium">{feature.desc}</p>
                
                <div className="mt-8 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-green-500 opacity-0 group-hover:opacity-100 transition-opacity">
                  Learn More <ChevronRight size={14} />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-20 px-6 bg-slate-900/50 border-t border-white/5 relative z-10">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-12 mb-16">
            <div className="col-span-2">
              <div className="flex items-center gap-3 mb-6">
                <img src="/logo.png" alt="Logo" className="w-8 h-8 opacity-80" />
                <span className="text-lg font-black tracking-tighter">INSTITUTE<span className="text-green-500">PULSE</span></span>
              </div>
              <p className="text-gray-400 max-w-sm mb-8 font-medium">The future of university management is sustainable, connected, and AI-driven. Join thousands of students making a difference every day.</p>
              <div className="flex gap-4">
                {[1, 2, 3, 4].map(i => (
                  <div key={i} className="w-10 h-10 rounded-full bg-white/5 border border-white/10 flex items-center justify-center hover:bg-green-500 transition-colors cursor-pointer" />
                ))}
              </div>
            </div>
            
            {[
              { title: 'Platform', links: ['Features', 'Bus Tracking', 'Eco System', 'Campus AI'] },
              { title: 'Company', links: ['About Us', 'Sustainability', 'Security', 'Contact'] }
            ].map(col => (
              <div key={col.title}>
                <h4 className="text-[10px] font-black uppercase tracking-[0.2em] mb-6 text-white">{col.title}</h4>
                <ul className="flex flex-col gap-4">
                  {col.links.map(link => (
                    <li key={link}><a href="#" className="text-sm font-medium text-gray-500 hover:text-green-500 transition-colors">{link}</a></li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          
          <div className="flex flex-wrap items-center justify-between gap-6 pt-12 border-t border-white/5">
            <p className="text-[10px] font-bold text-gray-600 uppercase tracking-widest">© 2026 InstitutePulse Technologies. All rights reserved.</p>
            <div className="flex gap-8">
              <a href="#" className="text-[10px] font-bold text-gray-600 uppercase tracking-widest hover:text-white transition-colors">Privacy Policy</a>
              <a href="#" className="text-[10px] font-bold text-gray-600 uppercase tracking-widest hover:text-white transition-colors">Terms of Service</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

